name: Android Production Template

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        required: false
        default: "17"
      java_distribution:
        type: string
        required: false
        default: "temurin"
    secrets:
      RELEASE_KEYSTORE_BASE64:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_ALIAS_RELEASE:
        required: true
      KEY_PASSWORD:
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: >
            platforms;android-34
            build-tools;34.0.0
            platform-tools
            ndk;25.2.9519653
            cmake;3.22.1

      - name: Obtener versión desde build.gradle
        id: version
        run: |
          #VERSION=$(grep "^version" build.gradle | cut -d '"' -f2)
          if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#release/}"      
          else
            # Caso 3: Cualquier otra rama
            VERSION="0.0.0"
          fi          
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      #- name: Configure Git
      #  run: |
      #    git config user.name "github-actions[bot]"
      #    git config user.email "github-actions[bot]@users.noreply.github.com"

      #- name: Crear tag
       # run: |
       #   git tag v${{ steps.version.outputs.version }}
       #   git push origin v${{ steps.version.outputs.version }}

      - name: Push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: v${{ steps.version.outputs.version }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Restore keystore
        run: |
          mkdir -p keystores
          echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > keystores/release.keystore
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

      - name: Build APK
        run: ./gradlew assembleRelease 
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS_RELEASE: ${{ secrets.KEY_ALIAS_RELEASE }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Resolve version name
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BUILD_NUMBER="${{ github.run_number }}"        
          if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            # Caso 2: Rama release/1.0.0 → 1.0.0
            VERSION="${{ github.ref_name }}"
            VERSION="${VERSION#release/}"      
          else
            # Caso 3: Cualquier otra rama
            VERSION="0.0.0"
          fi

          APK_PATH="app/build/outputs/apk/release/app-release.apk"
          NEW_NAME="${REPO_NAME}-delivery-${BUILD_NUMBER}-${VERSION}.apk"
      
          mv "$APK_PATH" "app/build/outputs/apk/release/$NEW_NAME"
          echo "NEW_NAME=$NEW_NAME" >> $GITHUB_ENV
          echo "APK renamed to $NEW_NAME"
    
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: delivery-apk
          path: app/build/outputs/apk/release/*.apk
          
